### ISSUE TITLE
Multiple assemblies with equivalent identity have been imported

### ISSUE THREAD

**Issue by constantinpopp** [immersivecognition/unity-experiment-framework#121]
Hi,
Have tried installing the UXF framework on Unity 2021.2.15f1 running on Windows. Unity complains that the System.Windows.Forms.dll is duplicated after the install of the UXF framework. This happens on the vanilla URP core template with the UXF being the first extra package to be installed.

> error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\const\Unity\TestUXF\Assets\UXF\Plugins\System.Windows.Forms.dll' and 'C:\Program Files\Unity\Hub\Editor\2021.2.15f1\Editor\Data\UnityReferenceAssemblies\unity-4.8-api\System.Windows.Forms.dll'. Remove one of the duplicate references.

If I remove the duplicate file from the UXF framework it breaks the framework.

Any help would be appreciated.  Best wishes
Constantin

**Comment by jackbrookes** [comment]
Hi, in general you should stick to LTS versions of Unity for UXF work - these are the most stable and what UXF is developed against. The Tech Stream versions have too many changes month-to-month that makes development difficult. The current LTS version is Unity 2020.

Its possible this is a bug with Unity:
https://githubmemory.com/repo/SrejonKhan/AnotherFileBrowser/issues/2

Perhaps it can be ignored? I will keep a look out for issues related to this.

**Comment by constantinpopp** [comment]
Ah, thanks for the link. This seems to be the same issue. I'll try this out. Many thanks.

**Comment by VissersR** [comment]
The 2021.3 LTS has been out for a month now, the issue is still there. The workaround I used is to copy the win32 version from the Unity 2021.3 directory over the existing version in the project. 

Not really happy that a dependency like WinForms is used in Unity to display a filebrowser that puts the focus outside of Unity. 
I think a Unity native filebrowser would be better in line with the unity architecture and user experience.

**Comment by AntonLimhamn** [comment]
Also working with the UXF Framework (v2.4.3) I ran into a strange problem related to the above. It is present in (at least) 2022.3.22f1 2022.3.32f1 2022.3.33f1  versions of Unity: When I install the UXF framework (JUST install), the View Tool in the Scene view does not work any more, The camera gizmo turns the scene alright, just the Hand movement does not work. It has something to do with System.Windows.Forms.dll : if I exclude it from the install, the View Tool works (but I get other problems). If I copy the dll from the Unity Editor (as suggested by VissersR above) it does not help either. So there is something more to it...
